---

spring:
  datasource:
    platform: h2
    initialize: true

    url: jdbc:h2:mem:testdb;Mode=Oracle;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 1081

logging:
  level:
    com.ml.logistica.romaneio: DEBUG

