spring:
  profiles:
        active: @spring.profiles.active@
---
spring:
  profiles: common

server:
  error:
    whitelabel.enabled: true
  port: 8080

logging:
  level:
    com.ml.logistica.romaneio: DEBUG

ml.logistica.api.romaneio:
  service:
    authToken: "##ZjYxY2FiZmJjMDRhN2I2YjJmMmExNjE3##"
    baseUrl: api/v1/packingLists


  packingList:
    queries:
      - { id: 1, name: "Traditional", query: "classpath:/dao/packingList/1-traditional.sql"}
      - { id: 2, name: "Courrier", query: "classpath:/dao/packingList/2-courrier.sql"}
      - { id: 3, name: "LuizaGol", query: "classpath:/dao/packingList/3-luizagol.sql"}

---

spring:
  profiles: h2
  datasource:
    platform: h2
    initialize: true
    url: jdbc:h2:mem:testdb;Mode=Oracle;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console
