spring:
  profiles:
        active: @spring.profiles.active@

server:
  error:
    whitelabel.enabled: true
  port: 8080

logging:
  level:
    com.ml.logistica.romaneio: DEBUG

ml.logistica.api.romaneio:
  service:
    authToken: "##ZjYxY2FiZmJjMDRhN2I2YjJmMmExNjE3##"
    baseUrl: api/v1/packingLists

  packingList:
    queries:
      - { id: 1, name: "Traditional", query: "classpath:/dao/packingList/1-traditional.sql"}
      - { id: 2, name: "Courrier", query: "classpath:/dao/packingList/2-courrier.sql"}
      - { id: 3, name: "LuizaGol", query: "classpath:/dao/packingList/3-luizagol.sql"}

