SELECT ROMANEIO.NUMROMANEIO NROMANEIO,
        ROMANEIO.CODFIL,
        'Courrier' TIPO,
        ROMANEIO.DTHRFECHAMENTO DATA_ROMANEIO,
        NULL CODVEIC,
        ITROMANEIO.NUMPEDVEN,
        LOTE.NLOTE
      
  FROM DIS_ROMANEIOPEDIDO   ROMANEIO,
        DIS_ITROMANEIOPEDIDO ITROMANEIO,
        DIS_LOTE                   LOTE,
        DIS_ITLOTE                 ITLOTE
 WHERE ROMANEIO.CODFIL = ITROMANEIO.CODFIL
   AND ROMANEIO.NUMROMANEIO = ITROMANEIO.NUMROMANEIO

   AND ITLOTE.CODFIL = ITROMANEIO.CODFIL
   AND ITLOTE.NUMPEDVEN = ITROMANEIO.NUMPEDVEN

   AND LOTE.CODFIL = ITLOTE.CODFIL
   AND LOTE.NLOTE = ITLOTE.NLOTE

   [:NROMANEIO][AND ROMANEIO.NUMROMANEIO = :NROMANEIO];
   [:CODFIL][AND ROMANEIO.CODFIL = :CODFIL];
   [:START_DATE][AND ROMANEIO.DTHRFECHAMENTO >= :START_DATE];
   [:END_DATE][AND ROMANEIO.DTHRFECHAMENTO <= :END_DATE];

