SELECT ROMANEIO.NROMANEIO,
        ROMANEIO.CODFIL,
        'Traditional' TIPO,
        LOTE.HRDTLOTE DATA_ROMANEIO,
        ROMANEIO.CODVEIC,
        ITLOTE.NUMPEDVEN,
        LOTE.NLOTE       
  FROM DIS_ROMANEIO   ROMANEIO,
        DIS_ITROMANEIO ITROMANEIO,
        DIS_LOTE       LOTE,
        DIS_ITLOTE     ITLOTE
 WHERE ROMANEIO.CODFIL = ITROMANEIO.CODFIL
   AND ROMANEIO.NROMANEIO = ITROMANEIO.NROMANEIO

   AND LOTE.CODFIL = ROMANEIO.CODFIL
   AND LOTE.NLOTE = ITROMANEIO.NLOTE

   AND LOTE.CODFIL = ITLOTE.CODFIL
   AND LOTE.NLOTE = ITLOTE.NLOTE


   [:NROMANEIO][AND ROMANEIO.NROMANEIO = :NROMANEIO];
   [:CODFIL][AND ROMANEIO.CODFIL = :CODFIL];
   [:START_DATE][AND LOTE.HRDTEXP > :START_DATE];
   [:END_DATE][AND LOTE.HRDTEXP < :END_DATE];
         
 ORDER BY NROMANEIO